const periods={day:{dials:128,talks:42,leads:7,rate:'5.5%',subtitle:'Today by hour',labels:['8','9','10','11','12','1','2','3','4'],values:[6,12,18,16,8,14,19,21,14],trends:['↑ 12% vs yesterday','32.8% contact rate','↑ 2 vs yesterday','Target 5.0%']},week:{dials:684,talks:219,leads:36,rate:'5.3%',subtitle:'This week by day',labels:['Mon','Tue','Wed','Thu','Fri'],values:[112,128,151,143,150],trends:['↑ 8% vs last week','32.0% contact rate','↑ 5 vs last week','Target 5.0%']},month:{dials:2846,talks:917,leads:154,rate:'5.4%',subtitle:'This month by week',labels:['W1','W2','W3','W4'],values:[612,748,706,780],trends:['↑ 6% vs last month','32.2% contact rate','↑ 18 vs last month','Target 5.0%']}};
const ids=['dials','talks','leads','rate'];
function renderPeriod(name){const data=periods[name],max=Math.max(...data.values);ids.forEach((id,i)=>{document.getElementById('metric-'+id).textContent=data[id];document.getElementById('trend-'+id).textContent=data.trends[i]});document.getElementById('chart-subtitle').textContent=data.subtitle;document.getElementById('chart-total').textContent=data.dials+' total';document.getElementById('activity-chart').innerHTML=data.values.map((value,i)=>`<div class="bar-wrap"><div class="bar ${i===data.values.length-2?'current':''}" style="height:${Math.max(10,value/max*92)}%"></div><small>${data.labels[i]}</small></div>`).join('')}
document.querySelectorAll('[data-period]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-period]').forEach(item=>item.classList.remove('active'));button.classList.add('active');renderPeriod(button.dataset.period)}));
document.querySelectorAll('[data-outcome]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.outcome.toLowerCase().replace(/ /g,'-'),count=document.getElementById('count-'+key);count.textContent=Number(count.textContent)+1;document.getElementById('log-feedback').textContent=button.dataset.outcome+' recorded · demo only';if(button.animate)button.animate([{transform:'scale(.97)'},{transform:'scale(1)'}],{duration:180})}));
const dismiss=document.querySelector('.announcement button');if(dismiss)dismiss.addEventListener('click',()=>dismiss.parentElement.remove());
const reveals=document.querySelectorAll('.reveal');if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.1});reveals.forEach(el=>observer.observe(el))}else{reveals.forEach(el=>el.classList.add('visible'))}
const demoThemeToggle=document.getElementById('demo-theme-toggle');const savedDemoTheme=localStorage.getItem('webstat_demo_theme')||'dark';document.documentElement.dataset.demoTheme=savedDemoTheme;if(demoThemeToggle){demoThemeToggle.textContent=savedDemoTheme==='dark'?'☀':'☾';demoThemeToggle.addEventListener('click',()=>{const next=document.documentElement.dataset.demoTheme==='dark'?'light':'dark';document.documentElement.dataset.demoTheme=next;localStorage.setItem('webstat_demo_theme',next);demoThemeToggle.textContent=next==='dark'?'☀':'☾'})}
const demoSideNav=document.querySelector('.side-nav');if(demoSideNav){demoSideNav.innerHTML='<button class="active" data-demo-page="overview">Overview</button><button data-demo-page="input">Input</button>';const main=document.querySelector('.dashboard-main'),announcement=document.querySelector('.announcement'),metrics=document.querySelector('.metrics'),panels=[...document.querySelectorAll('.dash-grid .panel')];function showDemoPage(page){demoSideNav.querySelectorAll('button').forEach(button=>button.classList.toggle('active',button.dataset.demoPage===page));main.classList.toggle('demo-page-mode',page==='input');if(announcement)announcement.style.display=page==='overview'?'flex':'none';metrics.style.display=page==='overview'?'grid':'none';panels.forEach(panel=>{const isInput=panel.classList.contains('quick-log');panel.style.display=(page==='input'?isInput:!isInput)?'block':'none'})}demoSideNav.addEventListener('click',event=>{const button=event.target.closest('[data-demo-page]');if(button)showDemoPage(button.dataset.demoPage)});showDemoPage('overview')}
renderPeriod('day');
